//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "GameLoadPage.xaml.h"

void ::Connect4___GUI::GameLoadPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///GameLoadPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Connect4___GUI::GameLoadPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->load_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->load_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::load_button_Click);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->load_button))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::PageLoaded);
        }
        break;
    case 3:
        {
            this->back_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->back_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::back_button_Click);
        }
        break;
    case 4:
        {
            this->username1_text = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 5:
        {
            this->password1_text = safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(__target);
        }
        break;
    case 6:
        {
            this->player1_ready_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->player1_ready_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::player1_ready_Click);
        }
        break;
    case 7:
        {
            this->username2_text = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 8:
        {
            this->password2_text = safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(__target);
        }
        break;
    case 9:
        {
            this->player2_ready_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->player2_ready_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::player2_ready_Click);
        }
        break;
    case 10:
        {
            this->error_text2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 11:
        {
            this->player1_ready_text = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->player2_ready_text = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 13:
        {
            this->p1_red = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_red))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_red_Click);
        }
        break;
    case 14:
        {
            this->p1_yellow = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_yellow))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_yellow_Click);
        }
        break;
    case 15:
        {
            this->p1_blue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_blue))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_blue_Click);
        }
        break;
    case 16:
        {
            this->p1_green = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_green))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_green_Click);
        }
        break;
    case 17:
        {
            this->p1_pink = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_pink))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_pink_Click);
        }
        break;
    case 18:
        {
            this->p1_purple = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_purple))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_purple_Click);
        }
        break;
    case 19:
        {
            this->p1_orange = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_orange))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_orange_Click);
        }
        break;
    case 20:
        {
            this->p1_brown = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p1_brown))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p1_brown_Click);
        }
        break;
    case 21:
        {
            this->p2_red = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_red))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_red_Click);
        }
        break;
    case 22:
        {
            this->p2_yellow = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_yellow))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_yellow_Click);
        }
        break;
    case 23:
        {
            this->p2_blue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_blue))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_blue_Click);
        }
        break;
    case 24:
        {
            this->p2_green = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_green))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_green_Click);
        }
        break;
    case 25:
        {
            this->p2_pink = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_pink))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_pink_Click);
        }
        break;
    case 26:
        {
            this->p2_purple = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_purple))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_purple_Click);
        }
        break;
    case 27:
        {
            this->p2_orange = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_orange))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_orange_Click);
        }
        break;
    case 28:
        {
            this->p2_brown = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->p2_brown))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GameLoadPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GameLoadPage::p2_brown_Click);
        }
        break;
    case 29:
        {
            this->lock_symbol = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Connect4___GUI::GameLoadPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


