//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "GamePage.xaml.h"

void ::Connect4___GUI::GamePage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///GamePage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Connect4___GUI::GamePage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->red_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 3:
        {
            this->yellow_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 4:
        {
            this->empty_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 5:
        {
            this->gb00 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 6:
        {
            this->gb01 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 7:
        {
            this->gb02 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 8:
        {
            this->gb03 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 9:
        {
            this->gb04 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 10:
        {
            this->gb05 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 11:
        {
            this->gb06 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 12:
        {
            this->gb10 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 13:
        {
            this->gb11 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 14:
        {
            this->gb12 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 15:
        {
            this->gb13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 16:
        {
            this->gb14 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 17:
        {
            this->gb15 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 18:
        {
            this->gb16 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 19:
        {
            this->gb20 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 20:
        {
            this->gb21 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 21:
        {
            this->gb22 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 22:
        {
            this->gb23 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 23:
        {
            this->gb24 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 24:
        {
            this->gb25 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 25:
        {
            this->gb26 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 26:
        {
            this->gb30 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 27:
        {
            this->gb31 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 28:
        {
            this->gb32 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 29:
        {
            this->gb33 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 30:
        {
            this->gb34 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 31:
        {
            this->gb35 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 32:
        {
            this->gb36 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 33:
        {
            this->gb40 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 34:
        {
            this->gb41 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 35:
        {
            this->gb42 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 36:
        {
            this->gb43 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 37:
        {
            this->gb44 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 38:
        {
            this->gb45 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 39:
        {
            this->gb46 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 40:
        {
            this->gb50 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 41:
        {
            this->gb51 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 42:
        {
            this->gb52 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 43:
        {
            this->gb53 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 44:
        {
            this->gb54 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 45:
        {
            this->gb55 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 46:
        {
            this->gb56 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 47:
        {
            this->column0_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column0_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column0_button_Click);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column0_button))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::game_loaded);
        }
        break;
    case 48:
        {
            this->column1_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column1_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column1_button_Click);
        }
        break;
    case 49:
        {
            this->column2_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column2_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column2_button_Click);
        }
        break;
    case 50:
        {
            this->column3_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column3_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column3_button_Click);
        }
        break;
    case 51:
        {
            this->column4_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column4_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column4_button_Click);
        }
        break;
    case 52:
        {
            this->column5_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column5_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column5_button_Click);
        }
        break;
    case 53:
        {
            this->column6_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->column6_button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Connect4___GUI::GamePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GamePage::column6_button_Click);
        }
        break;
    case 54:
        {
            this->display = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 55:
        {
            this->turn_display = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 56:
        {
            this->player_display = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 57:
        {
            this->blue_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 58:
        {
            this->purple_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 59:
        {
            this->pink_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 60:
        {
            this->green_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 61:
        {
            this->brown_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 62:
        {
            this->orange_color = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 63:
        {
            this->player1_c = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 64:
        {
            this->player2_c = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Connect4___GUI::GamePage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


