#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
                ref class PasswordBox;
                ref class TextBlock;
            }
        }
    }
}

namespace Connect4___GUI
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class GameLoadPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class GameLoadPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Button^ load_button;
        private: ::Windows::UI::Xaml::Controls::Button^ back_button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ username1_text;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ password1_text;
        private: ::Windows::UI::Xaml::Controls::Button^ player1_ready_button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ username2_text;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ password2_text;
        private: ::Windows::UI::Xaml::Controls::Button^ player2_ready_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ error_text2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ player1_ready_text;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ player2_ready_text;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_red;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_yellow;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_blue;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_green;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_pink;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_purple;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_orange;
        private: ::Windows::UI::Xaml::Controls::Button^ p1_brown;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_red;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_yellow;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_blue;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_green;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_pink;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_purple;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_orange;
        private: ::Windows::UI::Xaml::Controls::Button^ p2_brown;
        private: ::Windows::UI::Xaml::Controls::Button^ lock_symbol;
    };
}

