#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class ListView;
                ref class TextBox;
                ref class TextBlock;
            }
        }
    }
}

namespace Connect4___GUI
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class LeaderboardPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class LeaderboardPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Button^ back_button;
        private: ::Windows::UI::Xaml::Controls::ListView^ PlayerScores;
        private: ::Windows::UI::Xaml::Controls::TextBox^ username_text;
        private: ::Windows::UI::Xaml::Controls::Button^ findplayer_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ rss;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r10n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r10s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r9n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r9s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r8n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r8s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r7n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r7s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r6n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r6s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r5n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r5s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r4n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r4s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r3s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r3n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r2s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r2n;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r1s;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ r1n;
    };
}

