#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
                ref class PasswordBox;
                ref class TextBlock;
            }
        }
    }
}

namespace Connect4___GUI
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Button^ play_button;
        private: ::Windows::UI::Xaml::Controls::Button^ leaderboard_button;
        private: ::Windows::UI::Xaml::Controls::Button^ quit_button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ username_text;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ password_text;
        private: ::Windows::UI::Xaml::Controls::Button^ addplayer_button;
        private: ::Windows::UI::Xaml::Controls::Button^ deletplayer_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ error_text;
    };
}

